version: '3'

services:
  # Database
  db:
    image: mysql
    volumes:
      - ./sql_scripts/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: no_password
      MYSQL_DATABASE: doudou
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
  # node
  node:
    depends_on:
      - db
    image: node
    restart: always
    volumes:
      - ./src/app/:/usr/src/app
    command:  bash -c "cd /usr/src/app && npm install && node server.js" 
    ports:
      - '8082:8080'
